var baseId = "appxPi2CoLTlsa3qL";
var tournament;
var activetournament;
var activeteam;
var activematch;
var matches;
var endplay;
var teams;
var activeorganizer;
var activesporttype;
var orgaNizer;
var SportList;
var clientID;
var previouspage;
var isInTurnament=false;
var iSAlreadyLoaded = false;